sac:
  alpha: 0.0003
  beta: 0.0003
  gamma: 0.99
  max_size: 100000
  tau: 0.001
  batch_size: 128
  reward_scale: 2
  max_action: 1
  min_action: -1
  checkpoint_dir: 'models/sac'

ddpg:
  alpha: 0.0001 
  beta: 0.001 
  tau: 0.001
  n_actions: 0
  input_dims: 0
  gamma: 0.99
  max_size: 100000
  fc1_dims: 400
  fc2_dims: 300 
  batch_size: 128
  max_action: 1
  min_action: -1
  checkpoint_dir: 'models/ddpg'

td3:
  alpha: 0.001
  beta: 0.001
  tau: 0.005 
  max_action: 1
  min_action: -1
  gamma: 0.99
  update_actor_interval: 2
  warmup: 0
  n_actions: 2
  max_size: 100000
  layer1_size: 400
  layer2_size: 300
  batch_size: 128
  noise: 0.1
  checkpoint_dir: 'models/td3'
